Feat: Insert correct json parameters

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -80,48 +80,48 @@ jobs:
       - name: Deploy via AWS SSM
         id: ssm_deploy
         run: |
-            cat <<EOF > ssm_params.json
-            {
-              "commands": [
-                "docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest",
-                "docker rm -f ${{ github.event.repository.name }} || true",
-                "cat <<'ENV_EOF' > app.env\n${{ secrets.ENVIRONMENT_VARIABLES }}\nENV_EOF",
-                "docker run -d --name ${{ github.event.repository.name }} --env-file app.env -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest",
-                "rm app.env"
-              ]
-            }
-            EOF
-    
-            echo "Sending command to EC2..."
-            COMMAND_ID=$(aws ssm send-command \
-              --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
-              --document-name "AWS-RunShellScript" \
-              --comment "Deploying Java App via GitHub Actions" \
-              --parameters file://ssm_params.json \
-              --query "Command.CommandId" \
-              --output text)
-    
-            echo "Command ID: \$COMMAND_ID"
-    
-            echo "Waiting for command execution..."
-            aws ssm wait command-executed \
-              --command-id "\$COMMAND_ID" \
-              --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
-    
-            # Validate the final execution status
-            STATUS=$(aws ssm get-command-invocation \
-              --command-id "\$COMMAND_ID" \
+          cat <<'EOF' > ssm_params.json
+          {
+            "commands": [
+              "docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest",
+              "docker rm -f ${{ github.event.repository.name }} || true",
+              "cat <<'ENV_EOF' > app.env\n${{ secrets.ENVIRONMENT_VARIABLES }}\nENV_EOF",
+              "docker run -d --name ${{ github.event.repository.name }} --env-file app.env -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest",
+              "rm app.env"
+            ]
+          }
+          EOF
+
+          echo "Sending command to EC2..."
+          COMMAND_ID=$(aws ssm send-command \
+            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
+            --document-name "AWS-RunShellScript" \
+            --comment "Deploying API" \
+            --parameters file://ssm_params.json \
+            --query "Command.CommandId" \
+            --output text)
+
+          echo "Command ID: $COMMAND_ID"
+
+          echo "Waiting for command execution..."
+          aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
+
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
+            --query "Status" \
+            --output text)
+
+          if [ "$STATUS" != "Success" ]; then
+            echo "Deployment failed with status: $STATUS"
+            aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
               --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
-              --query "Status" \
-              --output text)
-    
-            if [ "\$STATUS" != "Success" ]; then
-              echo "Deployment failed with status: \$STATUS"
-              aws ssm get-command-invocation \
-                --command-id "\$COMMAND_ID" \
-                --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
-                --query "StandardErrorContent" \
-                --output text
-              exit 1
-            fi
-            echo "Deployment successful!"
+              --query "StandardErrorContent" \
+              --output text
+            exit 1
+          fi
+
+          echo "Deployment successful!"
