Feat: Add AWS SSM to initialize deploy

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -77,47 +77,43 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
 
-      - name: Push SSH key via Instance Connect
-        id: ssh_setup
+      - name: Deploy via AWS SSM
+        id: ssm
         run: |
-          ssh-keygen -t rsa -b 4096 -m PEM -f github-actions-key -N ""
-          echo "PRIVATE_KEY<<EOF" >> $GITHUB_OUTPUT
-          cat github-actions-key >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
-          
-          EC2_AZ=$(aws ec2 describe-instances \
-          --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
-          --query "Reservations[0].Instances[0].Placement.AvailabilityZone" \
-          --output text)
-          
-          aws ec2-instance-connect send-ssh-public-key \
-            --instance-id ${{ secrets.EC2_INSTANCE_ID }} \
-            --availability-zone $EC2_AZ \
-            --instance-os-user ${{ secrets.EC2_USER }} \
-            --ssh-public-key file://github-actions-key.pub
-
-      - name: Deploy via SSH
-        uses: appleboy/ssh-action@v1.0.0
-        with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ steps.ssh_setup.outputs.PRIVATE_KEY }}
-          script: |
-            echo "Pulling application latest Docker image"
-            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
-            
-            echo "Stopping previous container..."
-            docker rm -f ${{ github.event.repository.name }} || true
-            
-            echo "Writing environment variables"
-            echo "${{ secrets.ENVIRONMENT_VARIABLES }}" > app.env
-            
-            echo "Starting new container..."
-            docker run -d \
-              --name ${{ github.event.repository.name }} \
-              --env-file app.env \
-              -p 80:8080 \
-              ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
-            
-            echo "Cleaning .env"
-            rm app.env
+          COMMAND_ID=$(aws ssm send-command \
+            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
+            --document-name "AWS-RunShellScript" \
+            --comment "Deploy API Container" \
+            --parameters '{
+              "commands": [
+                "docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest",
+                "docker rm -f ${{ github.event.repository.name }} || true",
+                "cat <<EOF > app.env\n${{ secrets.ENVIRONMENT_VARIABLES }}\nEOF",
+                "docker run -d --name ${{ github.event.repository.name }} --env-file app.env -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest",
+                "rm app.env"
+              ]
+            }' \
+            --query "Command.CommandId" \
+            --output text)
+        
+          echo "Command ID: $COMMAND_ID"
+        
+          echo "Waiting finished deploy."
+          aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.EC2_INSTANCE_ID }}"
+        
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
+            --query "Status" \
+            --output text)
+        
+          if [ "$STATUS" != "Success" ]; then
+            echo "Error in deploy! Status: $STATUS"
+            aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
+              --query "{Status:Status,Output:StandardOutputContent,Error:StandardErrorContent}"
+            exit 1
+          fi
